### ISSUE TITLE
Docker Build Command Fails

### ISSUE THREAD

**Issue by billabrian6** [danives/FFTCGDB#13]
I'm interested in contributing to your project, but after following the instructions I noticed the docker build fails after it attempts to start the MySQL database.

` * Starting MySQL database server mysqld
   ...fail!
The command '/bin/sh -c rm -rf /var/www &&mv /tmp/FFTCG /var/www &&composer install -d /var/www &&mv /var/www/.env.example /var/www/.env &&sed -i -n '/.*REDIS.*/!p' /var/www/.env &&sed -i -n '/.*MAIL.*/!p' /var/www/.env &&sed -i -n '/.*PUSHER.*/!p' /var/www/.env &&sed -i 's/DB_DATABASE=.*/DB_DATABASE=fftcgdb/g' /var/www/.env &&sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/g' /var/www/.env &&sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=/g' /var/www/.env &&sed -i 's|/var/www/html|/var/www/public|g' /etc/apache2/sites-enabled/* &&(cd /var/www && php artisan key:generate) &&sed -i 's/.*max_input_vars = .*/max_input_vars = 65534/g' /etc/php/5.6/apache2/php.ini &&echo "log_errors = On" >> /etc/php/5.6/apache2/php.ini &&echo "error_reporting = E_ALL" >> /etc/php/5.6/apache2/php.ini &&service mysql start &&mysql -u root -e "CREATE DATABASE fftcgdb /*\!40100 DEFAULT CHARACTER SET utf8 */;" &&mysql -u root -D fftcgdb < /var/www/fftcgdb.sql &&(cd /var/www && php artisan migrate) &&mysql -u root -D fftcgdb < /var/www/cards.sql &&mkdir -p /var/www/storage/logs/ &&touch /var/www/storage/logs/laravel.log &&chown -R www-data:www-data /var/www &&rm -rf /var/www/*.sql' returned a non-zero code: 1`

I'm running the newest version of docker on OSX 10.11.6.

**Comment by HandsomeStrife** [comment]
@nfraker maybe you can help with this seeing as I'm unfamiliar with Docker?

**Comment by nfraker** [comment]
@billabrian6 hey, let me try with the newest docker; they made some breaking changes when they switched to the monthly CE builds a little while back and my laptop is running a release from before that.

**Comment by billabrian6** [comment]
@nfraker No problem. Thanks for taking a look at it. If you can't get it to work. Please post the docker version that you're using, and I'll downgrade.

**Comment by nfraker** [comment]
@billabrian6 it's definitely due to the new docker version; it's got to do with how docker is managing mysql's data directory, which it considers volatile space (because docker believes all files inside the container are such unless you specifically indicate they aren't.) I'm going to take a look tomorrow (it's just after midnight here), I see some improvements I can poach from the official MySQL 5.7 container while I'm at it which should help with new docker versions.

I'm also going to port these containers over to docker hub when I'm done so you can just pull latest. I'll update when I have more info

**Comment by nfraker** [comment]
@billabrian6 So, fun fact, the problem here is something we ran into at my work last Monday; with Docker CE's switch to a monthly build cycle they also switched the default filesystem driver from DeviceMapper to OverlayFS2 (it works very similarly to Docker's concept of intermediate build layers, so they like it). The problem is OverlayFS2 doesn't acknowledge the changes being made during build-time to MySQL's binary-encoded data directory, and so when MySQL requests the files off the disk OverlayFS2 renders them improperly, making MySQL barf on its shoes.

The fix is, I kid you not, to `touch` the contents of the data directory just prior to starting mysqld, to stop OverlayFS2 from thinking there might be newer versions of the data directory on some previous layer.

I've got a "corrected" lamp_base at https://hub.docker.com/r/ikaruwa/lamp_base/ and a test version of this repo's Dockerfile at https://hub.docker.com/r/ikaruwa/fftcgdb/. I've also submitted a PR (#14) so you can build locally.

As I said in the PR, note that you no longer need to build the lamp_base layer, your Docker service will pull that from the Docker registry.

**Comment by billabrian6** [comment]
@nfraker Awesome. I will make another attempt. Thanks for the help.

**Comment by nfraker** [comment]
@billabrian6 sure! Let me know if I can be any help. Thanks for the interest in the site!

P.s., by default docker is setting allocated ram for the container to 2gb, I've found it needs more like 4 due to all the moving pieces in that base layer it's built on

**Comment by billabrian6** [comment]
@nfraker Thanks for fixing this and the advice.

**Comment by billabrian6** [comment]
@nfraker Is there a symlink missing from the container to the workspace? Frontend changes that I'm making aren't showing up on the webpage. To check I used bash through docker to 'cat' the files, and my changes weren't there.

**Comment by nfraker** [comment]
@billabrian6 the container does not by default map a volume between the repo and the container, it instead copies the contents of the repo into the container and then makes some modifications to config files once they're no longer inside a tracked directory. This is why your changes on your workstation aren't being reflected. My work method is to start the container up and then `docker cp </file/path> fftcgdb:<path>` over my ~/.gitconfig and git credentials and then just work from /var/www, since the repo's `.git` directory will be present in /var/www. But I also do all my work in Vim because I'm weird like that.

If you want to map your repo checkout into the container you can do that at docker runtime. the command would look something like:

> `docker run --rm -d --privileged -p 80:80 -v </path/to/repo/on/your/workstation>:/var/www:rw --name fftcgdb --hostname fftcgdb ikaruwa/fftcgdb:latest`

If you do this you'll have to do the following steps inside the container* manually:
```
composer install -d /var/www
cp /var/www/.env.example /var/www/.env
sed -i -n '/.*REDIS.*/!p' /var/www/.env
sed -i -n '/.*MAIL.*/!p' /var/www/.env
sed -i -n '/.*PUSHER.*/!p' /var/www/.env
sed -i 's/DB_DATABASE=.*/DB_DATABASE=fftcgdb/g' /var/www/.env
sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/g' /var/www/.env
sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=/g' /var/www/.env
sed -i 's|/var/www/html|/var/www/public|g' /etc/apache2/sites-enabled/*
(cd /var/www && php artisan key:generate)
```
(*TBH, you could do the editing of the .env file inside your workspace, but if you do it all in the container you can get away with copy/pasting the codeblock above)

If you do this please make sure not to check in the .env file (i don't know if it's in .gitignore, but it should be).
